### ISSUE TITLE
Retrieving value from json file (which including Object & Array)

### ISSUE THREAD

**Issue by amharfm** [UmbraEngineering/json-file#4]
Salam.
How do you retrieving a value from json file (which including Object & Array)?

**Comment by kbjr** [comment]
Values can be retrieved from a file using the `read` and `get` methods. If you have a file `data.json` with the following content:

``` json
{
    "foo": {
        "bar": {
            "baz": [1, 2, 3]
        }
    }
}
```

You can pull that array from the file like so:

``` javascript
var json = require('json-file');

var arr = json.read('data.json').get('foo.bar.baz');  // returns array [1, 2, 3]
```

Is there something else you don't understand?

**Comment by amharfm** [comment]
what if the array is object also?

{
'a' : 'a',
'b': [
[{ 'a':'a', 'b' : [0,1,2,3] }]
[{object2}]
]
}

because it looks like that .get('b[1].b[2]') didnt worked. or even .set( )

i'll try your solution and see if that's right solution.
i was in Node when i'm stucked at: 
var json = require("json-file")

var json_map= json.read("player/adam/map_0'.json", function(){
    var one = json_map.get('layers')[7];
    var two = json_map.get('layers')[7].data;
    var three = json_map.get('layers')[7].data[500]; //is this also sufficient for modifying the value?

```
console.log(json_peta);
```

});

**Comment by amharfm** [comment]
Or maybe json-file won't be the solution?
You wrote the dot (.) character as split-er; without the array index pointer. cmiiw.
//  Property editing
File.prototype.get = function(key) {
    return this._resolve(key, function(scope, key, value) {
        return value;
    });
};

File.prototype.set = function(key, value) {
    this._resolve(key, function(scope, key) {
        scope[key] = value;
    });
    return this;
};

// Has a callback, but is NOT async
File.prototype._resolve = function(key, callback) {
    var current = this.data;
    var keys = key.split('.');                                                  //this line
    key = keys.pop();
    keys.forEach(function(key) {
        current = current[key];
    });
    return callback(current, key, current[key]);
};

**Comment by kbjr** [comment]
You should use the dot notation in all cases. So, instead of

``` javascript
.get('b[1].b[2]')
```

you should use

``` javascript
.get('b.1.b.2')
```

array indexes are still just object properties, and can be used the same way in this case.

**Comment by amharfm** [comment]
Subhanallah..
my baaad. Thanks a lot James :-D
